let questionNumber = 0;
let score = 0;

function updateQuestionNumber() {
  questionNumber++;
  $('.question-number').html(questionNumber);
}

function renderQuestionInDOM() {
  updateQuestionNumber();
  $('.quiz-forms').html(generateQuestion());
}

//question will be generated by calling from STORE array

function generateQuestion() {
  if (questionNumber <= STORE.length) {
  return `<div class="js-question-group">
            <form>
            <fieldset>
              <legend>${STORE[questionNumber - 1].question}</legend>
              
              <div class="questionOption">
              <input id="answer1" type="radio" value="${STORE[questionNumber - 1].answers[0]}" name="answer" required tabindex="0">
              <label for="answer1">${STORE[questionNumber - 1].answers[0]}</label>
              </div>
             
             <div class="questionOption">
              <input id="answer2" type="radio" value="${STORE[questionNumber - 1].answers[1]}" name="answer" required tabindex="0">
              <label for="answer2">${STORE[questionNumber - 1].answers[1]}</label>
              </div>
              
              <div class="questionOption">
              <input id="answer3" type="radio" value="${STORE[questionNumber - 1].answers[2]}" name="answer" required tabindex="0">
              <label for="answer3">${STORE[questionNumber - 1].answers[2]}</label>
              </div>
              
              <div class="questionOption">
              <input id="answer4" type="radio" value="${STORE[questionNumber - 1].answers[3]}" name="answer" required tabindex="0">
              <label for="answer4">${STORE[questionNumber - 1].answers[3]}</label>
              </div>
              
              <button type="submit" class="submitButton" value="Submit" required>Submit</button>
            </fieldset>
            </form>
          </div>`;
  }
  else {
    displayResults();
    $('.questionNumber').text(10);
  }
}


//determine if user answers question correctly 
//compare user input with correctAnswer
function handleFormSubmit() {
    $('.quiz-forms').submit(function (event) {
      event.preventDefault();
      let answer = $('input:checked').val();
      let correctAnswer = `${STORE[questionNumber - 1].correctAnswer}`;
      if (answer === correctAnswer) {
        ifAnswerIsCorrect();
      }
      else {
        ifAnswerIsWrong();
      }
    });
}

function ifAnswerIsCorrect () {
  userAnswerFeedbackCorrect();
  updateScore();
}

function ifAnswerIsWrong () {
  userAnswerFeedbackWrong();
}

//user feedback for correct answer
function userAnswerFeedbackCorrect () {
  let correctAnswer = `${STORE[questionNumber - 1].correctAnswer}`;
  $(".js-question-group").html(`<div class="js-user-answer-feedback correct">
  <h2>You are correct!</h2>
  <button class="next-button">Next</button>
  <div class="feedbackGIF"><img src="https://i.makeagif.com/media/3-19-2018/22T8Fl.gif" alt="Ballerina receives applause"></div></div>`);
}

//user feedback for wrong answer
function userAnswerFeedbackWrong () {
  let correctAnswer = `${STORE[questionNumber - 1].correctAnswer}`;
  $(".js-question-group").html(`<div class="js-user-answer-feedback incorrect">
  <h2>Sorry, that is incorrect! The answer is ${correctAnswer}.</h2>
  <button class="next-button">Next</button>
  <div class="feedbackGIF"><img src="https://i.makeagif.com/media/3-19-2018/CTPYYq.gif" alt="ballet dancer falls during pirouette"></div</div>`);
}

//incrementing one if user is correct
function changeScore() {
  score++;
 // return score;
}

function updateScore() {
  changeScore();
  $('.score').text(score);
}


function handleNextClick() {
  $('.quiz-forms').on('click', '.next-button', function(event) {
    
    renderQuestionInDOM();
  });
}


//after the last question is answered, user will click to see results
function displayResults() {
  if (`${score}` >= 8) {
    $('.quiz-forms').html(`<div class="quiz-results"><h2>Great Job! Your score is ${score}/10</h2><button class="quiz-restart">Start Over</button></div>`);
    }
  else if (`${score}` > 5) {
    $('.quiz-forms').html(`<div class="quiz-results"><h2>Good Job! Your score is ${score}/10</h2><button class="quiz-restart">Start Over</button></div>`);
    }
  else {
    $('.quiz-forms').html(`<div class="quiz-results" style="color:#f7dcdc"><h2>Your score is ${score}/10. Maybe Google "ballet" and read up on it a little bit, then try this quiz again!</h2><button class="quiz-restart">Start Over</button></div>`);
    }
  
  $('.question-number').text(10);
}


function restartQuiz() {
  $('.quiz-container').on('click', '.quiz-restart', function (event) {
    location.reload();
  });
}

//event listener for when user clicks 'begin quiz' button
function handleBeginQuizClicked() {
  $('.start-page').on('click', `.begin-quiz-button`, function(event) {
    $('.start-page').remove();
    renderQuestionInDOM();
    $('.question-number').text(1);
  });
}

function doTheQuiz() {
  handleBeginQuizClicked();
  handleFormSubmit();
  handleNextClick();
  restartQuiz();
}


$(doTheQuiz);








